### ISSUE TITLE
IndexError if _ready is given an argument

### ISSUE THREAD

**Issue by rcorre** [calviken/vim-gdscript3#13]
I'm getting the following error while typing into a gdscript file:

```
Error detected while processing function GDScriptComplete[15]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rcorre/dotfiles/nvim/plugged/vim-gdscript3/ftplugin/../python/init.py", line 31, in gdscript_complete
    completer.complete_script(include_globals=True)
  File "/home/rcorre/dotfiles/nvim/plugged/vim-gdscript3/ftplugin/../python/completer.py", line 124, in complete_script
    for decl in script.iter_decls(util.get_cursor_line_num(), direction=-1):
  File "/home/rcorre/dotfiles/nvim/plugged/vim-gdscript3/ftplugin/../python/script.py", line 188, in _iter_decls_up
    mapped_args = _args_to_vars(decl)
  File "/home/rcorre/dotfiles/nvim/plugged/vim-gdscript3/ftplugin/../python/script.py", line 89, in _args_to_vars
    method_arg = method.args[i]

Press ENTER or type command to continue
Error detected while processing function GDScriptComplete[15]..provider#python3#Call:
line   18:
IndexError: list index out of range
```

neovim: v0.3.4 (+acl +iconv +jemalloc +tui)
Python: 3.7.2
godot: `3.0.6.stable.custom_build`
vim-gdscript: bc79c41
completion: lifepillar/vim-mucomplete@62a2453

The following will trigger it:

```
func _ready(delta):  # delta is a copy-paste typo
	| type anything here |
```

`_ready` shouldn't have an argument, but it would be nice if `vim-gdscript` didn't explode.

**Comment by calviken** [comment]
Should be fixed now. It panicked anytime there were too many arguments in an overridden function. It tried to look up the type of each argument without checking whether the argument actually existed in the base function.

**Comment by rcorre** [comment]
Can't repro on master any more, thanks!
